services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: prod
    restart: unless-stopped
    ports:
      - ${PORT}:${PORT}
    environment:
      APP_ENV: ${APP_ENV}
      PORT: ${PORT}
      URLSHORT_DB_PORT: ${URLSHORT_DB_PORT}
      URLSHORT_DB_ADDRESS: ${URLSHORT_DB_ADDRESS}
      URLSHORT_DB_PASSWORD: ${URLSHORT_DB_PASSWORD}
      URLSHORT_DB_DATABASE: ${URLSHORT_DB_DATABASE}
    depends_on:
      redis_bp:
        condition: service_healthy
    networks:
      - blueprint
  redis_bp:
    image: redis:7.2.4
    restart: unless-stopped
    ports:
      - "${URLSHORT_DB_PORT}:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 3
      start_period: 15s
    networks:
      - blueprint

networks:
  blueprint:
